#!/usr/bin/env bash

set -eu

branch_name="$(git symbolic-ref --short HEAD 2>/dev/null || :)"
if [ -n "${branch_name:-}" ] \
        && [ "$branch_name" != "master" ] \
        && ! grep -q '^Merge branch' "$1"; then
    sed -i'' -e "1s%^%$branch_name | %" "$1"
fi
