#!/usr/bin/env bash
set -eu

branch="$(git symbolic-ref -q --short HEAD 2>/dev/null)" && {
    if ! grep -q "^Merge branch\|^${branch} |" "$1" && test "$branch" != 'master'; then
        sed -i'' -e "1s%^%${branch} | %" "$1"
    fi
} || :
